const nutritionMap = {
  "Egg (Whole)": {
    quantity: { value: 1, unit: "" },
    energy_kcal: 70,
    protein_g: 6,
    carbohydrates_g: 0.6,
    fats_g: 5,
    vitamins: {
      A: "6%",
      D: "10%",
      E: "4%",
      B1: "2%",
      B2: "15%",
      B3: "2%",
      B5: "7%",
      B6: "5%",
      B7: "23%",
      B9: "5%",
      B12: "12%",
    },
    minerals: {
      Ca: "22 mg",
      Fe: "1.2 mg",
      Mg: "6 mg",
      K: "63 mg",
      Na: "64 mg",
      Zn: "0.4 mg",
    },
  },
  "Egg White": {
    quantity: { value: 1, unit: "" },
    energy_kcal: 17,
    protein_g: 4,
    carbohydrates_g: 0.2,
    fats_g: 0,
    vitamins: {
      B2: "9%",
      B5: "2%",
      B6: "2%",
      B7: "2%",
      B9: "1%",
    },
    minerals: {
      Na: "55 mg",
      Zn: "0.1 mg",
    },
  },
  "Peanuts (boiled)": {
    quantity: { value: 100, unit: "g" },
    energy_kcal: 245,
    protein_g: 10.6,
    carbohydrates_g: 16.1,
    fats_g: 18.6,
    vitamins: {
      E: "9%",
      B1: "12%",
      B3: "28%",
      B5: "24%",
      B6: "22%",
      B9: "76%",
    },
    minerals: {
      Ca: "29 mg",
      Fe: "2.2 mg",
      Mg: "92 mg",
      K: "365 mg",
      Na: "18 mg",
      Zn: "1.9 mg",
    },
  },
  "Green gram (boiled)": {
    quantity: { value: 100, unit: "g" },
    energy_kcal: 116,
    protein_g: 8.9,
    carbohydrates_g: 20.8,
    fats_g: 0.4,
    vitamins: {
      B1: "7%",
      B2: "4%",
      B3: "2%",
      B5: "9%",
      B6: "7%",
      B9: "56%",
    },
    minerals: {
      Ca: "25 mg",
      Fe: "1.4 mg",
      Mg: "47 mg",
      K: "266 mg",
      Zn: "1.4 mg",
    },
  },
  "Ladies finger (boiled)": {
    quantity: { value: 100, unit: "g" },
    energy_kcal: 33,
    protein_g: 1.9,
    carbohydrates_g: 7,
    fats_g: 0.2,
    vitamins: {
      A: "14%",
      C: "25%",
      K: "53%",
      B1: "6%",
      B2: "2%",
      B3: "3%",
      B5: "2%",
      B6: "2%",
      B9: "8%",
    },
    minerals: {
      Ca: "99 mg",
      Fe: "0.8 mg",
      Mg: "57 mg",
      K: "303 mg",
      Na: "7 mg",
      Zn: "0.6 mg",
    },
  },
  "White rice": {
    quantity: { value: 100, unit: "g" },
    energy_kcal: 130,
    protein_g: 2.7,
    carbohydrates_g: 28.2,
    fats_g: 0.3,
    vitamins: {
      B1: "5%",
      B3: "3%",
      B5: "3%",
      B6: "6%",
      B9: "2%",
    },
    minerals: {
      Fe: "0.4 mg",
      Mg: "12 mg",
      K: "35 mg",
      Zn: "0.3 mg",
    },
  },
  Roti: {
    quantity: { value: 1, unit: "" },
    energy_kcal: 70,
    protein_g: 2,
    carbohydrates_g: 15,
    fats_g: 0.4,
    vitamins: {
      B1: "2%",
      B2: "2%",
      B3: "6%",
      B5: "1%",
      B6: "1%",
      B9: "2%",
    },
    minerals: {
      Fe: "0.8 mg",
      Mg: "15 mg",
      K: "48 mg",
      Zn: "0.6 mg",
    },
  },
  "Chicken breast": {
    quantity: { value: 100, unit: "g" },
    energy_kcal: 165,
    protein_g: 31,
    carbohydrates_g: 0,
    fats_g: 3.6,
    vitamins: {
      B3: "35%",
      B5: "6%",
      B6: "30%",
      B12: "8%",
    },
    minerals: {
      Mg: "24 mg",
      K: "256 mg",
      Na: "74 mg",
      Zn: "0.6 mg",
    },
  },
  Banana: {
    quantity: { value: 1, unit: "" },
    energy_kcal: 105,
    protein_g: 1.3,
    carbohydrates_g: 27,
    fats_g: 0.4,
    vitamins: {
      A: "1%",
      C: "17%",
      B1: "4%",
      B2: "5%",
      B3: "4%",
      B5: "7%",
      B6: "21%",
      B9: "5%",
    },
    minerals: {
      Mg: "27 mg",
      K: "358 mg",
      Zn: "0.2 mg",
    },
  },
  Paneer: {
    quantity: { value: 100, unit: "g" },
    energy_kcal: 265,
    protein_g: 18.3,
    carbohydrates_g: 1.2,
    fats_g: 20.8,
    vitamins: {
      A: "18%",
      B2: "10%",
      B5: "2%",
      B12: "5%",
    },
    minerals: {
      Ca: "208 mg",
      Na: "54 mg",
      Zn: "1.2 mg",
    },
  },
  Curd: {
    quantity: { value: 100, unit: "g" },
    energy_kcal: 98,
    protein_g: 3.6,
    carbohydrates_g: 3.4,
    fats_g: 7.1,
    vitamins: {
      B2: "7%",
      B5: "3%",
      B12: "3%",
    },
    minerals: {
      Ca: "123 mg",
      K: "159 mg",
      Na: "56 mg",
      Zn: "0.9 mg",
    },
  },
  Milk: {
    quantity: { value: 100, unit: "g" },
    energy_kcal: 42,
    protein_g: 3.4,
    carbohydrates_g: 4.8,
    fats_g: 1,
    vitamins: {
      A: "5%",
      B2: "10%",
      B5: "2%",
      B12: "18%",
    },
    minerals: {
      Ca: "113 mg",
      K: "150 mg",
      Na: "42 mg",
      Zn: "0.4 mg",
    },
  },
  "Almonds (soaked)": {
    quantity: { value: 10, unit: "g" },
    energy_kcal: 21.4,
    protein_g: 0.47,
    carbohydrates_g: 0.52,
    fats_g: 2,
    vitamins: {
      E: "175%",
      B2: "60%",
      B3: "17%",
      B5: "24%",
      B6: "8%",
      B9: "50%",
    },
    minerals: {
      Ca: "7.3 mg",
      Fe: "0.11 mg",
      Mg: "7.6 mg",
      K: "20.8 mg",
      Zn: "0.06 mg",
    },
  },
  Pistachios: {
    quantity: { value: 10, unit: "g" },
    energy_kcal: 56.2,
    protein_g: 2.02,
    carbohydrates_g: 2.72,
    fats_g: 4.54,
    vitamins: {
      A: "7%",
      C: "7%",
      E: "4%",
      B1: "17%",
      B2: "6%",
      B3: "27%",
      B5: "13%",
      B6: "28%",
      B9: "25%",
    },
    minerals: {
      Ca: "10.5 mg",
      Fe: "0.39 mg",
      Mg: "12.1 mg",
      K: "102.5 mg",
      Zn: "0.22 mg",
    },
  },
  "Cashew nuts": {
    quantity: { value: 10, unit: "g" },
    energy_kcal: 55.3,
    protein_g: 1.82,
    carbohydrates_g: 3.02,
    fats_g: 4.39,
    vitamins: {
      B1: "37%",
      B2: "6%",
      B3: "1%",
      B5: "9%",
      B6: "20%",
      B9: "7%",
    },
    minerals: {
      Fe: "0.67 mg",
      Mg: "29.2 mg",
      K: "66 mg",
      Zn: "0.58 mg",
    },
  },
  Oats: {
    quantity: { value: 100, unit: "g" },
    energy_kcal: 389,
    protein_g: 16.9,
    carbohydrates_g: 66.3,
    fats_g: 6.9,
    fiber_g: 10.6,
    vitamins: {
      B1: "55%",
      B2: "15%",
      B3: "37%",
      B5: "10%",
      B6: "15%",
      B9: "56%",
    },
    minerals: {
      Ca: "54 mg",
      Fe: "4.72 mg",
      Mg: "177 mg",
      K: "429 mg",
      Na: "2 mg",
      Zn: "4.2 mg",
    },
  },
  Walnut: {
    quantity: { value: 10, unit: "g" },
    energy_kcal: 65.4,
    protein_g: 1.52,
    carbohydrates_g: 1.37,
    fats_g: 6.52,
    vitamins: {
      E: "6%",
      B1: "18%",
      B2: "2%",
      B3: "3%",
      B5: "11%",
      B6: "32%",
      B9: "21%",
    },
    minerals: {
      Ca: "9.8 mg",
      Fe: "0.29 mg",
      Mg: "15.8 mg",
      K: "44.1 mg",
      Zn: "0.29 mg",
    },
  },

  "Soya chunks": {
    quantity: { value: 100, unit: "g" },
    energy_kcal: 336,
    protein_g: 52.8,
    carbohydrates_g: 33.8,
    fats_g: 0.5,
    vitamins: {
      B1: "62%",
      B2: "20%",
      B3: "13%",
      B5: "11%",
      B6: "31%",
      B9: "78%",
    },
    minerals: {
      calcium: "240 mg",
      iron: "15.7 mg",
      magnesium: "282 mg",
      phosphorus: "705 mg",
      potassium: "1797 mg",
      sodium: "20 mg",
      zinc: "5 mg",
    },
  },

  Apple: {
    quantity: { value: 100, unit: "g" },
    energy_kcal: 52,
    protein_g: 0.3,
    carbohydrates_g: 14,
    fats_g: 0.2,
    fiber_g: 2.4,
    vitamins: {
      A: "1%",
      C: "7%",
      K: "2%",
      B1: "2%",
      B2: "2%",
      B3: "1%",
      B5: "2%",
      B6: "3%",
      B9: "1%",
    },
    minerals: {
      Ca: "6 mg",
      Fe: "0.1 mg",
      Mg: "5 mg",
      K: "107 mg",
      Na: "1 mg",
      Zn: "0.04 mg",
    },
  },
  Dates: {
    quantity: { value: 10, unit: "g" },
    energy_kcal: 33.6,
    protein_g: 0.2,
    carbohydrates_g: 8.8,
    fats_g: 0,
    fiber_g: 0.6,
    vitamins: {
      B1: "1%",
      B2: "1%",
      B3: "1%",
      B5: "1%",
      B6: "1%",
      B9: "1%",
    },
    minerals: {
      Ca: "6.8 mg",
      Fe: "0.1 mg",
      Mg: "8 mg",
      K: "48.5 mg",
      Na: "0.1 mg",
      Zn: "0.03 mg",
    },
  },
  "Peanut butter": {
    quantity: { value: 1, unit: "tbsp" },
    energy_kcal: 124,
    protein_g: 5,
    carbohydrates_g: 3.5,
    fats_g: 10,
    vitamins: {
      E: "10%",
      B3: "13%",
      B6: "6%",
    },
    minerals: {
      Ca: "10 mg",
      Fe: "0.5 mg",
      Na: "75 mg",
      K: "140 mg",
    },
  },
};

const nutritionList = [...Object.entries(nutritionMap)].map(
  ([itemName, value]) => ({
    itemName,
    ...value,
  })
);

export default nutritionList;
